(function(){
'use strict';
const path=location.pathname.toLowerCase();
const slug=path.includes('/eptc/')?'eptc':'demhab';
const portal=slug==='eptc'?'EPTC — Técnico em Processos Administrativos e Contábeis':'DEMHAB — Assistente Administrativo';
const shortPortal=slug==='eptc'?'EPTC':'DEMHAB';
const KEY=`${slug}:central-ia:v3`;
const PREV_KEY=`${slug}:central-ia:v2`;
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const nowIso=()=>new Date().toISOString();
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function toast(msg){let t=$('#aiToast');if(!t){t=document.createElement('div');t.id='aiToast';t.className='ai-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function moduleData(){try{return typeof modules!=='undefined'&&Array.isArray(modules)?[...modules].sort((a,b)=>(a.priority||0)-(b.priority||0)):[]}catch(_){return[]}}
const moduleList=moduleData();
function syllabusData(){let order=0;return moduleList.flatMap(m=>m.topics.map((title,index)=>({key:`${m.id}|${index}`,order:order++,moduleId:m.id,moduleName:m.name,title,index})))}
const syllabus=syllabusData();
function initialState(){return{version:3,items:[],difficulty:'medio',activeModuleId:'',activeTopicKey:'',activeItemId:'',view:'home',tab:'estudo',createdAt:nowIso()}}
function readState(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s?.version===3)return s}catch(_){}
 const s=initialState();try{const old=JSON.parse(localStorage.getItem(PREV_KEY));if(old?.items?.length){s.items=old.items.map(x=>({...x,chat:Array.isArray(x.chat)?x.chat:[],questionSets:Array.isArray(x.questionSets)?x.questionSets:[],attempts:Array.isArray(x.attempts)?x.attempts:[],notebookSyncedAt:x.notebookSyncedAt||'',notebookSourceTitle:x.notebookSourceTitle||'',updatedAt:x.updatedAt||nowIso(),createdAt:x.createdAt||nowIso()}));s.activeItemId=old.activeId||s.items[0]?.id||'';const a=s.items.find(x=>x.id===s.activeItemId);if(a?.topicKey){s.activeTopicKey=a.topicKey;s.activeModuleId=a.moduleId||a.topicKey.split('|')[0];s.view='room'}}localStorage.setItem(KEY,JSON.stringify(s))}catch(_){}return s}
let app=readState();
function persist(){localStorage.setItem(KEY,JSON.stringify(app))}
function activeTopic(){return syllabus.find(t=>t.key===app.activeTopicKey)||null}
function activeModule(){return moduleList.find(m=>m.id===app.activeModuleId)||null}
function activeItem(){return app.items.find(x=>x.id===app.activeItemId)||null}
function topicItems(topicKey){return app.items.filter(x=>x.topicKey===topicKey).sort((a,b)=>new Date(b.updatedAt||b.createdAt)-new Date(a.updatedAt||a.createdAt))}
function topicAttempts(topicKey){return topicItems(topicKey).flatMap(x=>(x.attempts||[]).map(a=>({...a,itemTitle:x.title,itemId:x.id}))).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))}
function topicSets(topicKey){return topicItems(topicKey).flatMap(x=>(x.questionSets||[]).map(q=>({...q,itemTitle:x.title,itemId:x.id}))).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))}
function topicStats(topicKey){const items=topicItems(topicKey),attempts=topicAttempts(topicKey);const q=items.reduce((n,x)=>n+(x.questionSets||[]).reduce((a,s)=>a+(s.questions?.length||0),0),0);const avg=attempts.length?Math.round(attempts.reduce((a,x)=>a+(x.percent||0),0)/attempts.length):null;return{lessons:items.length,questions:q,attempts:attempts.length,avg}}
function moduleStats(moduleId){const topics=syllabus.filter(t=>t.moduleId===moduleId);const s=topics.map(t=>topicStats(t.key));const attempts=s.reduce((n,x)=>n+x.attempts,0);const weighted=s.filter(x=>x.avg!==null);return{lessons:s.reduce((n,x)=>n+x.lessons,0),attempts,avg:weighted.length?Math.round(weighted.reduce((n,x)=>n+x.avg,0)/weighted.length):null}}
function assignTopic(item,t){if(!t){item.topicKey='';item.topicTitle='Não classificado';item.topicOrder=9999;item.moduleId='';item.moduleName='';return}Object.assign(item,{topicKey:t.key,topicTitle:t.title,topicOrder:t.order,moduleId:t.moduleId,moduleName:t.moduleName})}
function matchTopic(title,content=''){const hay=normalize(`${title} ${String(content).slice(0,5000)}`);let best=null,bestScore=0;for(const t of syllabus){const words=normalize(t.title).split(' ').filter(w=>w.length>3);if(!words.length)continue;let hits=0;for(const w of words)if(hay.includes(w))hits++;const score=hits/words.length+(hay.includes(normalize(t.title))?2:0);if(score>bestScore){best=t;bestScore=score}}return bestScore>=.28?best:null}
function ensureItem(data,forcedTopic){let x=app.items.find(i=>i.id===data.id);if(!x){x={id:data.id||uid('ai'),title:data.title||'Aula do Gran',source:data.source||'Gran Cursos',content:data.content||'',topicKey:'',topicTitle:'Não classificado',topicOrder:9999,moduleId:'',moduleName:'',chat:[],questionSets:[],attempts:[],notebookSyncedAt:'',notebookSourceTitle:'',createdAt:nowIso(),updatedAt:nowIso()};assignTopic(x,forcedTopic||matchTopic(x.title,x.content));app.items.push(x)}else{Object.assign(x,data,{updatedAt:nowIso()});if(forcedTopic)assignTopic(x,forcedTopic)}app.activeItemId=x.id;if(x.topicKey){app.activeTopicKey=x.topicKey;app.activeModuleId=x.moduleId}persist();return x}
function difficultyLabel(v){return v==='dificil'?'Difícil':v==='misto'?'Misto':'Médio'}
function baseRules(x){return `Você está auxiliando na preparação para ${portal} dentro do NotebookLM / Gemini Notebook. Use somente as fontes disponíveis no notebook. Concentre-se na fonte correspondente à aula "${x.title}" e no tópico do edital "${x.topicTitle||'Não classificado'}". Preserve a terminologia e o nível de detalhe das fontes. Se as fontes não sustentarem uma afirmação, diga isso claramente. Escreva em português do Brasil, com foco em concurso público.`}
function promptForTool(x,tool){const map={resumo:'Produza um resumo completo e estruturado seguindo a ordem do tópico. Destaque conceitos, distinções, prazos, exceções, exemplos e pegadinhas sustentadas pelas fontes.',mapa:'Crie um mapa mental textual hierárquico, com tema central, ramos, sub-ramos e relações entre conceitos sustentadas pelas fontes.',flashcards:'Crie 20 cartões didáticos em formato Pergunta | Resposta, priorizando recuperação ativa e pontos que confundem em prova.',revisao:'Monte uma revisão ativa com síntese curta, perguntas de recuperação e pontos para revisar.'};return `${baseRules(x)}\n\nTAREFA:\n${map[tool]||map.resumo}\n\nOrganize a resposta para estudo e use as citações do NotebookLM quando disponíveis.`}
function promptForChat(x,q){return `${baseRules(x)}\n\nPERGUNTA DO ALUNO:\n${q}\n\nResponda de forma didática e objetiva. Quando útil, relacione a resposta com a posição do assunto dentro do tópico do edital.`}
function promptForQuestions(x,difficulty){return `${baseRules(x)}\n\nTAREFA:\nCrie 10 questões autorais de múltipla escolha em nível ${difficultyLabel(difficulty).toUpperCase()}, com 5 alternativas cada. Para nível difícil, use distinções finas, exceções e situações-problema sustentadas pelas fontes.\n\nAo final, inclua a linha PORTAL_JSON e, logo abaixo, um único objeto JSON válido exatamente nesta estrutura:\n{"title":"...","difficulty":"${difficulty}","questions":[{"id":"q1","enunciado":"...","alternativas":["A...","B...","C...","D...","E..."],"correctIndex":0,"comentario":"..."}]}\ncorrectIndex deve ser inteiro de 0 a 4. Não inclua informações que não estejam nas fontes.`}
function promptForAttempt(x,set,attempt,wrong){return `${baseRules(x)}\n\nREGISTRO DE DESEMPENHO DO ALUNO:\nConjunto: ${set.title||'Questões'}\nDificuldade: ${difficultyLabel(attempt.difficulty)}\nResultado: ${attempt.correct}/${attempt.total} (${attempt.percent}%).\nQuestões erradas ou não respondidas: ${wrong.length?wrong.map(w=>`${w.number}. ${w.enunciado}`).join(' | '):'nenhuma'}.\n\nCrie uma nota curta de revisão com o desempenho e o que merece revisão com base somente nas fontes e neste resultado.`}
function parsePortalJson(text){const raw=String(text||'');const pos=raw.lastIndexOf('PORTAL_JSON');const part=pos>=0?raw.slice(pos):raw;const a=part.indexOf('{'),b=part.lastIndexOf('}');if(a<0||b<=a)return null;try{return JSON.parse(part.slice(a,b+1))}catch(_){return null}}
function safeName(s){return (s||'material').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)||'material'}
function notebookMarkdown(x){const parts=[`# ${x.title}`,'',`**Portal:** ${portal}`,`**Tópico:** ${x.topicTitle||'Não classificado'}`,`**Fonte:** ${x.source||'Gran Cursos'}`,'','## Material-base','',x.content||'_Sem material._'];if(x.chat?.length){parts.push('','## Discussão e explicações','');x.chat.forEach(m=>parts.push(`### ${m.role==='user'?'Pergunta':'Resposta'}`,'',m.text,''))}if(x.attempts?.length){parts.push('','## Resultados de questões','');x.attempts.forEach(a=>parts.push(`- ${new Date(a.createdAt).toLocaleString('pt-BR')}: ${a.correct}/${a.total} (${a.percent}%) — ${difficultyLabel(a.difficulty)}`))}return parts.join('\n')}
function download(name,text){const blob=new Blob([text],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),800)}
function addStyles(){const s=document.createElement('style');s.textContent=`
.ai-toast{position:fixed;right:22px;bottom:22px;z-index:10050;background:#f1f3f4;color:#202124;border-radius:12px;padding:11px 14px;font-size:12px;font-weight:750;opacity:0;transform:translateY(8px);transition:.2s;max-width:420px;box-shadow:0 8px 28px #0007}.ai-toast.show{opacity:1;transform:none}
.ai-launch{margin-top:20px;border:1px solid var(--line,#343434);background:linear-gradient(145deg,#23252b,#1d1f24);border-radius:20px;padding:22px}.ai-launch-inner{display:flex;align-items:center;justify-content:space-between;gap:18px}.ai-launch h3{margin:0;font-size:23px}.ai-launch p{margin:6px 0 0;color:#9da2ad;font-size:12px;max-width:720px}.ai-btn{border:1px solid #3a3d45;background:#282b32;color:#f2f3f5;border-radius:999px;padding:9px 14px;font-size:12px;font-weight:750;cursor:pointer}.ai-btn:hover{background:#31343c}.ai-btn.primary{background:#f1f3f4;color:#202124;border-color:#f1f3f4}.ai-btn.icon{width:38px;height:38px;padding:0;display:grid;place-items:center}.ai-file{display:none}
.ai-workspace{position:fixed;inset:0;z-index:10000;background:#202124;color:#e8eaed;display:none;grid-template-rows:64px minmax(0,1fr);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif}.ai-workspace.open{display:grid}.ai-topbar{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:0 24px;border-bottom:1px solid #3c4043;background:#202124}.ai-brand{display:flex;align-items:center;gap:14px;min-width:0}.ai-logo{width:34px;height:34px;border-radius:9px;background:#303134;display:grid;place-items:center;font-size:18px}.ai-brand-copy{min-width:0}.ai-brand-copy strong{display:block;font-size:14px}.ai-brand-copy small{display:block;color:#9aa0a6;font-size:10px;margin-top:2px}.ai-top-actions{display:flex;gap:8px;align-items:center}.ai-status-pill{border:1px solid #3c4043;border-radius:999px;padding:7px 10px;color:#aeb4bd;font-size:10px;white-space:nowrap}
.ai-stage{overflow:auto;padding:28px 32px 54px}.ai-shell{max-width:1180px;margin:0 auto}.ai-page-title{display:flex;justify-content:space-between;align-items:end;gap:16px;margin-bottom:20px}.ai-page-title h2{font-size:28px;line-height:1.1;margin:0;letter-spacing:-.02em}.ai-page-title p{margin:6px 0 0;color:#9aa0a6;font-size:12px}.ai-search{width:min(360px,100%);height:42px;border:1px solid #3c4043;border-radius:999px;background:#292a2d;color:#e8eaed;padding:0 16px;outline:none}.ai-search:focus{border-color:#8ab4f8}
.ai-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.ai-card{border:1px solid #3c4043;background:#292a2d;border-radius:18px;min-height:178px;padding:18px;cursor:pointer;transition:.16s;display:flex;flex-direction:column}.ai-card:hover{transform:translateY(-2px);border-color:#5f6368;background:#303134}.ai-card-top{display:flex;align-items:center;justify-content:space-between;gap:10px}.ai-card-icon{width:44px;height:44px;border-radius:12px;background:#202124;border:1px solid #3c4043;display:grid;place-items:center;font-size:19px}.ai-card-num{color:#8ab4f8;font-size:11px;font-weight:800}.ai-card h3{font-size:17px;line-height:1.28;margin:20px 0 6px}.ai-card p{font-size:11px;color:#9aa0a6;margin:0}.ai-card-meta{margin-top:auto;padding-top:16px;display:flex;gap:10px;flex-wrap:wrap;color:#bdc1c6;font-size:10px}.ai-chip{border:1px solid #3c4043;background:#25262a;color:#bdc1c6;border-radius:999px;padding:6px 9px;font-size:10px}.ai-chip.active{background:#384457;border-color:#6686b5;color:#fff}
.ai-breadcrumb{display:flex;gap:7px;align-items:center;color:#9aa0a6;font-size:11px;margin-bottom:14px}.ai-breadcrumb button{border:0;background:transparent;color:#9aa0a6;padding:0;cursor:pointer}.ai-breadcrumb button:hover{color:#e8eaed}.ai-topic-hero{border:1px solid #3c4043;background:#292a2d;border-radius:18px;padding:20px 22px;margin-bottom:14px;display:flex;align-items:center;justify-content:space-between;gap:18px}.ai-topic-hero h2{margin:0 0 5px;font-size:24px}.ai-topic-hero p{margin:0;color:#9aa0a6;font-size:11px}.ai-room-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.ai-tabs{display:flex;gap:8px;border-bottom:1px solid #3c4043;margin:0 0 16px;padding:0 2px}.ai-tab{border:0;background:transparent;color:#9aa0a6;padding:11px 10px;border-bottom:2px solid transparent;font-size:12px;font-weight:750;cursor:pointer}.ai-tab.active{color:#e8eaed;border-color:#8ab4f8}
.ai-panel{border:1px solid #3c4043;background:#292a2d;border-radius:16px;padding:17px}.ai-panel h4{margin:0 0 10px;font-size:14px}.ai-panel p{margin:0;color:#9aa0a6;font-size:11px;line-height:1.55}.ai-lessons{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-bottom:14px}.ai-lesson{border:1px solid #3c4043;background:#25262a;border-radius:14px;padding:13px;cursor:pointer;min-height:92px}.ai-lesson.active{background:#30394a;border-color:#6b86b6}.ai-lesson b{display:block;font-size:11px;line-height:1.35}.ai-lesson small{display:block;color:#8f949d;font-size:9px;margin-top:7px}.ai-tool-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:14px}.ai-tool{border:1px solid #3c4043;background:#292a2d;border-radius:14px;padding:14px;text-align:left;color:#e8eaed;cursor:pointer}.ai-tool:hover{background:#303134}.ai-tool b{display:block;font-size:11px}.ai-tool small{display:block;color:#9297a0;font-size:9px;margin-top:4px}.ai-tool .emoji{font-size:18px;margin-bottom:10px;display:block}
.ai-chat{display:flex;flex-direction:column;gap:10px;max-height:48vh;overflow:auto;padding:4px 2px 12px}.ai-msg{max-width:86%;border:1px solid #3c4043;border-radius:14px;padding:11px 13px;font-size:12px;line-height:1.55;white-space:pre-wrap}.ai-msg.user{align-self:flex-end;background:#30394a}.ai-msg.assistant{align-self:flex-start;background:#25262a}.ai-empty{border:1px dashed #4a4d52;border-radius:14px;padding:24px;text-align:center;color:#969ba4;font-size:11px}.ai-composer{margin-top:12px;border:1px solid #4a4d52;background:#25262a;border-radius:24px;padding:7px;display:grid;grid-template-columns:1fr auto;gap:8px}.ai-composer textarea{background:transparent;color:#e8eaed;border:0;outline:0;resize:none;min-height:42px;max-height:130px;padding:8px 9px}.ai-source-state{font-size:10px;color:#81c995;margin-top:6px}.ai-source-state.pending{color:#fdd663}
.ai-quiz-list,.ai-results-list{display:grid;gap:10px}.ai-row-card{border:1px solid #3c4043;background:#292a2d;border-radius:14px;padding:14px;display:flex;align-items:center;justify-content:space-between;gap:14px}.ai-row-card b{font-size:12px}.ai-row-card small{display:block;color:#9aa0a6;font-size:10px;margin-top:4px}.ai-score{font-size:20px;font-weight:850;white-space:nowrap}.ai-difficulty{display:flex;gap:7px;flex-wrap:wrap;margin:10px 0 16px}.ai-q{border:1px solid #3c4043;background:#292a2d;border-radius:14px;padding:14px;margin-bottom:10px}.ai-q strong{display:block;font-size:12px;line-height:1.5;margin-bottom:8px}.ai-opt{display:block;padding:6px 0;font-size:11px;color:#d6d9df}.ai-feedback{margin-top:8px;border-top:1px solid #3c4043;padding-top:8px;font-size:10px;color:#aab0ba}.ai-import-zone{border:1px dashed #5f6368;border-radius:16px;padding:28px;text-align:center}.ai-import-zone h4{margin:0 0 6px}.ai-import-zone p{margin:0 0 14px;color:#9aa0a6;font-size:11px}.ai-sep{height:1px;background:#3c4043;margin:14px 0}.ai-note{color:#9aa0a6;font-size:10px}.ai-hidden{display:none!important}
@media(max-width:980px){.ai-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.ai-tool-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.ai-lessons{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:650px){.ai-stage{padding:18px 14px 40px}.ai-topbar{padding:0 12px}.ai-brand-copy small,.ai-status-pill{display:none}.ai-grid,.ai-lessons,.ai-tool-grid{grid-template-columns:1fr}.ai-page-title,.ai-topic-hero{align-items:stretch;flex-direction:column}.ai-room-actions{justify-content:flex-start}.ai-search{width:100%}.ai-top-actions .ai-btn:not(.icon){display:none}}
`;document.head.appendChild(s)}
function addLauncher(){const nav=$('.nav');if(nav&&!nav.querySelector('[data-ai-open]')){const a=document.createElement('a');a.href='#';a.dataset.aiOpen='1';a.textContent='Sala IA';nav.appendChild(a)}if($('#ia-launch'))return;const sec=document.createElement('section');sec.id='ia-launch';sec.className='section ai-launch';sec.innerHTML=`<div class="ai-launch-inner"><div><h3>Sala IA — ${shortPortal}</h3><p>Escolha primeiro a área e o tópico. Cada tópico abre seu próprio espaço de estudo, com aulas do Gran, NotebookLM, questões e resultados separados.</p><div class="ai-note" id="aiConnectorState" style="margin-top:9px">Conector: verificando…</div></div><button class="ai-btn primary" id="aiOpenWorkspace">Abrir tópicos</button></div>`;const main=$('main.content')||$('main');const anchor=main?.querySelector('footer');if(main)anchor?main.insertBefore(sec,anchor):main.appendChild(sec)}
function addWorkspace(){if($('#aiWorkspace'))return;const w=document.createElement('div');w.id='aiWorkspace';w.className='ai-workspace';w.innerHTML=`<header class="ai-topbar"><div class="ai-brand"><div class="ai-logo">▣</div><div class="ai-brand-copy"><strong>${shortPortal} — Sala IA</strong><small>${esc(portal)}</small></div></div><div class="ai-top-actions"><span class="ai-status-pill" id="aiTopStatus">Conector verificando…</span><button class="ai-btn" id="aiOpenNotebook">NotebookLM</button><button class="ai-btn" id="aiSettings">Configurar</button><button class="ai-btn icon" id="aiClose" aria-label="Fechar">✕</button></div></header><div class="ai-stage"><div class="ai-shell" id="aiScreen"></div></div><input id="aiFile" class="ai-file" type="file" accept=".txt,.md,.vtt,.srt,text/plain,text/markdown,text/vtt">`;document.body.appendChild(w)}
function openWorkspace(view){if(view)app.view=view;persist();render();$('#aiWorkspace').classList.add('open');document.body.style.overflow='hidden'}
function closeWorkspace(){$('#aiWorkspace').classList.remove('open');document.body.style.overflow=''}
function showHome(){app.view='home';app.activeModuleId='';app.activeTopicKey='';persist();render()}
function showModule(id){app.view='topics';app.activeModuleId=id;app.activeTopicKey='';persist();render()}
function showTopic(key,tab='estudo'){const t=syllabus.find(x=>x.key===key);if(!t)return;app.view='room';app.activeModuleId=t.moduleId;app.activeTopicKey=t.key;app.tab=tab;const items=topicItems(t.key);if(!items.some(x=>x.id===app.activeItemId))app.activeItemId=items[0]?.id||'';persist();render()}
function homeScreen(){return `<div class="ai-page-title"><div><h2>Tópicos de estudo</h2><p>${shortPortal} separado em áreas. Entre em uma área para ver somente os tópicos dela.</p></div><input class="ai-search" id="aiSearch" placeholder="Buscar área ou tópico…"></div><div class="ai-grid" id="aiCardGrid">${moduleList.map((m,i)=>{const s=moduleStats(m.id);return `<article class="ai-card" data-module="${esc(m.id)}" data-search="${esc(normalize(m.name+' '+m.topics.join(' ')))}"><div class="ai-card-top"><div class="ai-card-icon">${i+1}</div><span class="ai-card-num">${m.topics.length} tópicos</span></div><h3>${esc(m.name)}</h3><p>Conteúdos organizados na ordem do edital deste concurso.</p><div class="ai-card-meta"><span>${s.lessons} aula${s.lessons===1?'':'s'}</span><span>${s.attempts} resultado${s.attempts===1?'':'s'}</span>${s.avg!==null?`<span>${s.avg}% média</span>`:''}</div></article>`}).join('')}</div>`}
function topicsScreen(){const m=activeModule();if(!m)return homeScreen();const topics=syllabus.filter(t=>t.moduleId===m.id);return `<div class="ai-breadcrumb"><button data-home>Início</button><span>›</span><span>${esc(m.name)}</span></div><div class="ai-page-title"><div><h2>${esc(m.name)}</h2><p>Escolha um tópico. Só depois entram aulas, conversa, questões e resultados daquele conteúdo.</p></div><input class="ai-search" id="aiSearch" placeholder="Buscar tópico…"></div><div class="ai-grid" id="aiCardGrid">${topics.map((t,i)=>{const s=topicStats(t.key);return `<article class="ai-card" data-topic="${esc(t.key)}" data-search="${esc(normalize(t.title))}"><div class="ai-card-top"><div class="ai-card-icon">${String(i+1).padStart(2,'0')}</div><span class="ai-card-num">Tópico ${String(i+1).padStart(2,'0')}</span></div><h3>${esc(t.title)}</h3><p>${s.lessons?`${s.lessons} aula${s.lessons===1?'':'s'} já vinculada${s.lessons===1?'':'s'}.`:'Nenhuma aula importada ainda.'}</p><div class="ai-card-meta"><span>${s.questions} questões</span><span>${s.attempts} tentativa${s.attempts===1?'':'s'}</span>${s.avg!==null?`<span>${s.avg}% média</span>`:''}</div></article>`}).join('')}</div>`}
function lessonCards(t){const items=topicItems(t.key);if(!items.length)return '<div class="ai-empty">Nenhuma aula neste tópico ainda.</div>';return `<div class="ai-lessons">${items.map(x=>`<div class="ai-lesson ${x.id===app.activeItemId?'active':''}" data-item="${x.id}"><b>${esc(x.title)}</b><small>${esc(x.source||'Gran Cursos')} • ${x.notebookSyncedAt?'NotebookLM ✓':'sincronização pendente'}</small></div>`).join('')}</div>`}
function studyTab(t){const x=activeItem();if(!x||x.topicKey!==t.key)return `<div class="ai-import-zone"><h4>Comece por uma aula deste tópico</h4><p>Abra a aula correspondente no Gran, deixe a transcrição visível e importe. Ela será salva somente em <b>${esc(t.title)}</b>.</p><div class="ai-actions" style="justify-content:center"><button class="ai-btn primary" id="aiGranDirect">Importar aula aberta no Gran</button><button class="ai-btn" id="aiImportFile">Importar arquivo</button></div></div>`;
 return `${lessonCards(t)}<div class="ai-panel" style="margin-bottom:14px"><div style="display:flex;justify-content:space-between;gap:12px;align-items:start"><div><h4>${esc(x.title)}</h4><p>${esc(x.source||'Gran Cursos')} • ${esc(t.title)}</p><div class="ai-source-state ${x.notebookSyncedAt?'':'pending'}">${x.notebookSyncedAt?'Fonte sincronizada com o NotebookLM':'Fonte ainda não sincronizada com o NotebookLM'}</div></div><div class="ai-actions"><button class="ai-btn" id="aiSyncSource">${x.notebookSyncedAt?'Sincronizar novamente':'Sincronizar fonte'}</button><button class="ai-btn" id="aiExport">Backup .md</button></div></div></div><div class="ai-tool-grid"><button class="ai-tool" data-tool="resumo"><span class="emoji">▤</span><b>Resumo</b><small>Síntese fundamentada nas fontes</small></button><button class="ai-tool" data-tool="mapa"><span class="emoji">⌘</span><b>Mapa mental</b><small>Estrutura conceitual do tópico</small></button><button class="ai-tool" data-tool="flashcards"><span class="emoji">▣</span><b>Cartões didáticos</b><small>Recuperação ativa</small></button><button class="ai-tool" data-tool="revisao"><span class="emoji">↻</span><b>Revisão ativa</b><small>Pontos para revisar</small></button></div><div class="ai-panel"><h4>Discussão e explicações</h4><div class="ai-chat" id="aiChat">${(x.chat||[]).map(m=>`<div class="ai-msg ${m.role}">${esc(m.text)}</div>`).join('')||'<div class="ai-empty">Faça uma pergunta sobre esta aula ou use uma das ferramentas acima. As respostas ficam salvas somente neste tópico.</div>'}</div><div class="ai-composer"><textarea id="aiQuestion" placeholder="Pergunte sobre este conteúdo…"></textarea><button class="ai-btn primary" id="aiAsk">Enviar</button></div></div>`}
function aulasTab(t){return `<div class="ai-panel" style="margin-bottom:14px"><h4>Aulas e fontes deste tópico</h4><p>Somente materiais de <b>${esc(t.title)}</b> aparecem aqui.</p><div style="margin-top:14px">${lessonCards(t)}</div></div><div class="ai-import-zone"><h4>Adicionar material</h4><p>Você pode trazer a aula aberta no Gran ou importar um arquivo de texto.</p><div class="ai-actions" style="justify-content:center"><button class="ai-btn primary" id="aiGranDirect">Importar aula aberta no Gran</button><button class="ai-btn" id="aiImportFile">Importar arquivo</button></div></div>`}
function questoesTab(t){const sets=topicSets(t.key);return `<div class="ai-panel" style="margin-bottom:14px"><h4>Gerar questões</h4><p>O NotebookLM cria questões usando as fontes vinculadas às aulas deste tópico.</p><div class="ai-difficulty"><button class="ai-chip ${app.difficulty==='medio'?'active':''}" data-diff="medio">Médio</button><button class="ai-chip ${app.difficulty==='dificil'?'active':''}" data-diff="dificil">Difícil</button><button class="ai-chip ${app.difficulty==='misto'?'active':''}" data-diff="misto">Misto</button></div><button class="ai-btn primary" id="aiGenerateQuestions">Gerar 10 questões</button></div><div class="ai-quiz-list">${sets.length?sets.map(s=>`<div class="ai-row-card"><div><b>${esc(s.title||'Questões')}</b><small>${esc(s.itemTitle)} • ${difficultyLabel(s.difficulty)} • ${s.questions?.length||0} questões</small></div><button class="ai-btn" data-open-set="${s.itemId}|${s.id}">Responder</button></div>`).join(''):'<div class="ai-empty">Nenhum conjunto de questões gerado neste tópico.</div>'}</div>`}
function resultadosTab(t){const attempts=topicAttempts(t.key);return `<div class="ai-results-list">${attempts.length?attempts.map(a=>`<div class="ai-row-card"><div><b>${esc(a.itemTitle)}</b><small>${new Date(a.createdAt).toLocaleString('pt-BR')} • ${difficultyLabel(a.difficulty)} • ${(a.wrong||[]).length} erro${(a.wrong||[]).length===1?'':'s'}${a.notebookSaved?' • NotebookLM ✓':''}</small></div><div class="ai-score">${a.percent}%</div></div>`).join(''):'<div class="ai-empty">Você ainda não respondeu questões neste tópico.</div>'}</div>`}
function roomScreen(){const t=activeTopic();if(!t){app.view='home';return homeScreen()}const m=moduleList.find(x=>x.id===t.moduleId);const st=topicStats(t.key);return `<div class="ai-breadcrumb"><button data-home>Início</button><span>›</span><button data-module-back="${esc(m.id)}">${esc(m.name)}</button><span>›</span><span>${esc(t.title)}</span></div><div class="ai-topic-hero"><div><h2>${esc(t.title)}</h2><p>${esc(m.name)} • ${st.lessons} aula${st.lessons===1?'':'s'} • ${st.attempts} resultado${st.attempts===1?'':'s'}${st.avg!==null?` • média ${st.avg}%`:''}</p></div><div class="ai-room-actions"><button class="ai-btn primary" id="aiGranDirect">+ Aula do Gran</button><button class="ai-btn" id="aiImportFile">Importar arquivo</button></div></div><div class="ai-tabs"><button class="ai-tab ${app.tab==='estudo'?'active':''}" data-tab="estudo">Estudo</button><button class="ai-tab ${app.tab==='aulas'?'active':''}" data-tab="aulas">Aulas</button><button class="ai-tab ${app.tab==='questoes'?'active':''}" data-tab="questoes">Questões</button><button class="ai-tab ${app.tab==='resultados'?'active':''}" data-tab="resultados">Resultados</button></div><div id="aiRoomContent">${app.tab==='aulas'?aulasTab(t):app.tab==='questoes'?questoesTab(t):app.tab==='resultados'?resultadosTab(t):studyTab(t)}</div>`}
function render(){const screen=$('#aiScreen');if(!screen)return;screen.innerHTML=app.view==='topics'?topicsScreen():app.view==='room'?roomScreen():homeScreen();bindScreen()}
function bindSearch(){const input=$('#aiSearch'),grid=$('#aiCardGrid');if(!input||!grid)return;input.oninput=()=>{const q=normalize(input.value);$$('[data-search]',grid).forEach(c=>c.classList.toggle('ai-hidden',q&&!c.dataset.search.includes(q)))}}
function bindScreen(){bindSearch();$$('[data-module]').forEach(c=>c.onclick=()=>showModule(c.dataset.module));$$('[data-topic]').forEach(c=>c.onclick=()=>showTopic(c.dataset.topic));$$('[data-home]').forEach(b=>b.onclick=showHome);$$('[data-module-back]').forEach(b=>b.onclick=()=>showModule(b.dataset.moduleBack));$$('[data-tab]').forEach(b=>b.onclick=()=>{app.tab=b.dataset.tab;persist();render()});$$('[data-item]').forEach(c=>c.onclick=()=>{app.activeItemId=c.dataset.item;app.tab='estudo';persist();render()});$$('[data-tool]').forEach(b=>b.onclick=()=>runTool(b.dataset.tool));$$('[data-diff]').forEach(b=>b.onclick=()=>{app.difficulty=b.dataset.diff;persist();render()});$$('[data-open-set]').forEach(b=>b.onclick=()=>{const [itemId,setId]=b.dataset.openSet.split('|');const x=app.items.find(i=>i.id===itemId),set=x?.questionSets?.find(s=>s.id===setId);if(x&&set){app.activeItemId=x.id;persist();renderQuiz(x,set)}});const gran=$('#aiGranDirect');if(gran)gran.onclick=()=>captureGranForTopic();const imp=$('#aiImportFile');if(imp)imp.onclick=()=>$('#aiFile').click();const ask=$('#aiAsk');if(ask)ask.onclick=askQuestion;const q=$('#aiQuestion');if(q)q.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')askQuestion()};const sync=$('#aiSyncSource');if(sync)sync.onclick=()=>{const x=activeItem();if(x)syncSource(x)};const exp=$('#aiExport');if(exp)exp.onclick=()=>{const x=activeItem();if(x){download(`${safeName(x.title)}-backup.md`,notebookMarkdown(x));toast('Backup Markdown gerado.')}};const gen=$('#aiGenerateQuestions');if(gen)gen.onclick=generateQuestions;setTimeout(()=>{const c=$('#aiChat');if(c)c.scrollTop=c.scrollHeight},0)}
function renderQuiz(x,set){const t=syllabus.find(t=>t.key===x.topicKey);const screen=$('#aiScreen');if(!screen)return;screen.innerHTML=`<div class="ai-breadcrumb"><button id="aiQuizBack">${esc(t?.title||'Voltar')}</button><span>›</span><span>${esc(set.title||'Questões')}</span></div><div class="ai-page-title"><div><h2>${esc(set.title||'Questões')}</h2><p>${difficultyLabel(set.difficulty)} • ${set.questions?.length||0} questões • resultado salvo neste tópico e sincronizado com o NotebookLM.</p></div></div><form id="aiQuiz">${(set.questions||[]).map((q,i)=>`<div class="ai-q"><strong>${i+1}. ${esc(q.enunciado)}</strong>${(q.alternativas||[]).map((a,j)=>`<label class="ai-opt"><input type="radio" name="q${i}" value="${j}"> ${esc(a)}</label>`).join('')}<div class="ai-feedback" id="fb${i}" hidden></div></div>`).join('')}<div class="ai-actions"><button type="button" class="ai-btn" id="aiQuizBack2">Voltar</button><button type="submit" class="ai-btn primary">Corrigir e salvar resultado</button></div></form>`;const back=()=>{app.tab='questoes';persist();render()};$('#aiQuizBack').onclick=back;$('#aiQuizBack2').onclick=back;$('#aiQuiz').onsubmit=e=>{e.preventDefault();let correct=0;const wrong=[];set.questions.forEach((q,i)=>{const sel=$(`input[name="q${i}"]:checked`,e.currentTarget);const idx=sel?Number(sel.value):-1,ok=idx===Number(q.correctIndex);if(ok)correct++;else wrong.push({number:i+1,enunciado:q.enunciado,selectedIndex:idx,correctIndex:Number(q.correctIndex)});const fb=$(`#fb${i}`);fb.hidden=false;fb.textContent=`${ok?'✓ Correto':'✗ Incorreto'} — ${q.comentario||''}`});const total=set.questions.length,percent=total?Math.round(correct/total*100):0;const attempt={id:uid('attempt'),questionSetId:set.id,correct,total,percent,difficulty:set.difficulty,wrong,createdAt:nowIso(),notebookSaved:false};x.attempts=x.attempts||[];x.attempts.push(attempt);x.updatedAt=nowIso();persist();toast(`Resultado salvo: ${correct}/${total} (${percent}%). Enviando ao NotebookLM…`);askNotebook('attempt',promptForAttempt(x,set,attempt,wrong),{itemId:x.id,attemptId:attempt.id})}}
let connectorConnected=false;const pending=new Map();
function connectorPost(type,payload={}){window.postMessage({source:'portal-de-estudos',type,...payload},location.origin)}
function setConnector(ok,text){connectorConnected=!!ok;const main=$('#aiConnectorState'),top=$('#aiTopStatus');if(main)main.textContent=text||`Conector: ${ok?'ativo':'não instalado'}`;if(top)top.textContent=text||`Conector: ${ok?'ativo':'não instalado'}`}
function queue(kind,meta,type,payload,notice){if(!connectorConnected){toast('Ative o Conector Gran + NotebookLM no Chrome.');return''}const requestId=`req-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;pending.set(requestId,{kind,meta});connectorPost(type,{requestId,...payload});if(notice)toast(notice);return requestId}
function syncSource(x){return queue('source',{itemId:x.id},'PORTAL_NOTEBOOK_SOURCE_REQUEST',{target:slug,title:`${x.topicTitle} — ${x.title}`,text:x.content},'Enviando a aula ao NotebookLM…')}
function askNotebook(kind,prompt,meta){return queue(kind,meta,'PORTAL_NOTEBOOK_QUERY_REQUEST',{target:slug,prompt,saveAsNote:true},'Consultando o NotebookLM…')}
function captureGranForTopic(){const t=activeTopic();if(!t){toast('Escolha um tópico primeiro.');return}queue('gran',{topicKey:t.key},'PORTAL_GRAN_CAPTURE_REQUEST',{},'Localizando a aula aberta no Gran…')}
function importCapture(r,forcedTopic){const t=forcedTopic||matchTopic(r.title,r.text);const x=ensureItem({title:r.title||'Aula do Gran',source:'Gran Cursos',content:r.text||''},t);if(!x.topicKey){toast('Não consegui identificar o tópico. Abra o tópico desejado e importe novamente.');return}app.view='room';app.tab='estudo';app.activeTopicKey=x.topicKey;app.activeModuleId=x.moduleId;persist();openWorkspace();toast(`Aula adicionada a “${x.topicTitle}”.`);syncSource(x)}
function askQuestion(){const x=activeItem(),q=$('#aiQuestion')?.value.trim();if(!x||!q)return;if(!x.notebookSyncedAt){toast('Sincronize a aula com o NotebookLM antes de perguntar.');syncSource(x);return}x.chat=x.chat||[];x.chat.push({id:uid('msg'),role:'user',text:q,createdAt:nowIso()});x.updatedAt=nowIso();persist();render();askNotebook('chat',promptForChat(x,q),{itemId:x.id})}
function runTool(tool){const x=activeItem();if(!x){toast('Importe ou selecione uma aula primeiro.');return}if(!x.notebookSyncedAt){toast('Sincronizando a fonte com o NotebookLM primeiro…');syncSource(x);return}askNotebook('tool',promptForTool(x,tool),{itemId:x.id,tool})}
function generateQuestions(){const a=activeItem();const x=(a?.topicKey===app.activeTopicKey?a:null)||topicItems(app.activeTopicKey)[0];if(!x){toast('Importe pelo menos uma aula neste tópico antes de gerar questões.');return}app.activeItemId=x.id;persist();if(!x.notebookSyncedAt){toast('Sincronizando a fonte com o NotebookLM primeiro…');syncSource(x);return}askNotebook('questions',promptForQuestions(x,app.difficulty),{itemId:x.id,difficulty:app.difficulty})}
window.addEventListener('message',ev=>{if(ev.source!==window||ev.origin!==location.origin||ev.data?.source!=='portal-conector-extension')return;const m=ev.data;if(m.type==='PORTAL_CONNECTOR_PONG'){setConnector(true,`Conector v${m.version||''} • NotebookLM`);return}if(m.type==='PORTAL_GRAN_PUSH'&&m.payload){importCapture(m.payload,null);connectorPost('PORTAL_GRAN_IMPORTED');return}if(m.type==='PORTAL_GRAN_CAPTURE_RESULT'){const p=pending.get(m.requestId);if(!p||p.kind!=='gran')return;pending.delete(m.requestId);if(!m.result?.ok){toast(m.result?.error||'Não foi possível localizar a aula do Gran.');return}const t=syllabus.find(x=>x.key===p.meta.topicKey)||null;importCapture(m.result,t);return}if(m.type==='PORTAL_NOTEBOOK_SOURCE_RESULT'){const p=pending.get(m.requestId);if(!p)return;pending.delete(m.requestId);const x=app.items.find(i=>i.id===p.meta.itemId);if(!x)return;const r=m.result;if(!r?.ok){toast(r?.error||'Não consegui adicionar a aula ao NotebookLM.');return}x.notebookSyncedAt=nowIso();x.notebookSourceTitle=r.sourceTitle||x.title;x.updatedAt=nowIso();persist();render();toast('Fonte salva no NotebookLM.');return}if(m.type==='PORTAL_NOTEBOOK_QUERY_RESULT'){const p=pending.get(m.requestId);if(!p)return;pending.delete(m.requestId);const r=m.result;if(!r?.ok){toast(r?.error||'Falha ao consultar o NotebookLM.');return}const x=app.items.find(i=>i.id===p.meta.itemId);if(!x)return;if(p.kind==='chat'||p.kind==='tool'){x.chat=x.chat||[];x.chat.push({id:uid('msg'),role:'assistant',text:r.text||'',kind:p.meta.tool||'chat',notebookSaved:!!r.savedAsNote,createdAt:nowIso()});x.updatedAt=nowIso();persist();app.tab='estudo';render();toast(r.savedAsNote?'Resposta salva no NotebookLM e no site.':'Resposta recebida no site.');return}if(p.kind==='questions'){const data=parsePortalJson(r.text);if(!data?.questions?.length){x.chat=x.chat||[];x.chat.push({id:uid('msg'),role:'assistant',text:r.text||'',notebookSaved:!!r.savedAsNote,createdAt:nowIso()});persist();app.tab='estudo';render();toast('O NotebookLM respondeu, mas não consegui montar as questões automaticamente. Salvei a resposta no estudo.');return}const set={id:uid('qset'),title:data.title||`Questões — ${x.title}`,difficulty:data.difficulty||p.meta.difficulty,questions:data.questions,notebookSaved:!!r.savedAsNote,createdAt:nowIso()};x.questionSets=x.questionSets||[];x.questionSets.push(set);x.updatedAt=nowIso();persist();renderQuiz(x,set);toast('Questões geradas e salvas.');return}if(p.kind==='attempt'){const a=(x.attempts||[]).find(a=>a.id===p.meta.attemptId);if(a){a.notebookSaved=!!r.savedAsNote;a.notebookNoteText=r.text||'';x.updatedAt=nowIso();persist()}toast(r.savedAsNote?'Resultado do estudo salvo no NotebookLM.':'Resultado salvo no site; não confirmei a nota no NotebookLM.');return}}});
function bindGlobal(){document.addEventListener('click',e=>{const a=e.target.closest('[data-ai-open]');if(a){e.preventDefault();openWorkspace('home')}});$('#aiOpenWorkspace').onclick=()=>openWorkspace('home');$('#aiClose').onclick=closeWorkspace;$('#aiOpenNotebook').onclick=()=>connectorPost('PORTAL_OPEN_NOTEBOOK',{target:slug});$('#aiSettings').onclick=()=>connectorPost('PORTAL_OPEN_CONNECTOR_OPTIONS');$('#aiFile').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const t=activeTopic();if(!t){toast('Escolha um tópico antes de importar o arquivo.');e.target.value='';return}const text=await f.text();const x=ensureItem({title:f.name.replace(/\.[^.]+$/,''),source:'Arquivo importado',content:text},t);app.view='room';app.tab='estudo';persist();render();syncSource(x);e.target.value=''}}
function init(){addStyles();addLauncher();addWorkspace();bindGlobal();render();connectorPost('PORTAL_CONNECTOR_PING');setTimeout(()=>{if(!connectorConnected)setConnector(false,'Conector: instale/ative a extensão')},1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
